# Generated by Django 5.2.9 on 2026-07-16 05:23

from django.db import migrations, models


def mark_existing_profiles_completed(apps, schema_editor):
    """Existing users predate this gate; don't lock them out on next login."""
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.update(profile_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_type',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'School (Classes 1-10)'), ('INTERMEDIATE', 'Intermediate (11-12)'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_profiles_completed, migrations.RunPython.noop),
    ]
