# Generated by Django 5.2.9 on 2026-07-17 08:50

from django.db import migrations, models


def approve_existing_profiles(apps, schema_editor):
    """New registrations start PENDING; accounts that already existed before
    this feature shipped should not be retroactively locked out."""
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.update(approval_status='APPROVED')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_education_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.RunPython(approve_existing_profiles, noop),
    ]
