# Generated by Django 5.2.9 on 2026-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('min_readiness', models.PositiveIntegerField(default=70, help_text='Minimum % readiness to suggest this job')),
                ('is_active', models.BooleanField(default=True)),
                ('required_skills', models.ManyToManyField(related_name='job_roles', to='courses.skill')),
            ],
        ),
    ]
